ci(Husky): Update pre-push hook

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -10,10 +10,14 @@ GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo '[None]')
 # Get version from `package.json`.
 PACKAGE=v$(grep -o '"version": "[^"]*"' package.json | sed 's/"version": "//;s/"//g')
 
-if [ "$GIT_TAG" != "$PACKAGE" ]; then
+# Get first version number listed in `CHANGELOG.md`.
+CHANGELOG=$(grep -oE '^v([0-9]+\.){2}[0-9]+' CHANGELOG.md | head -n 1 | sed 's/^### //')
+
+if [ "$GIT_TAG" != "$PACKAGE" ] || [ "$PACKAGE" != "$CHANGELOG" ]; then
   echo 'Version mismatch detected:' >&2
   echo "  - Git Tag:      $GIT_TAG" >&2
   echo "  - package.json: $PACKAGE" >&2
+  echo "  - CHANGELOG.md: $CHANGELOG" >&2
   echo 'Please update all version references to match.' >&2
   exit 1
 fi
@@ -21,12 +25,12 @@ fi
 ################################################################################
 # Check changelog date
 ################################################################################
-# if grep -qE "^### ${README} \([0-9]{4}-[0-9]{1,2}-[0-9]{1,2}\)" README.md; then
-#   :
-# else
-#   echo 'README.md: Missing or invalid date in the Changelog.'
-#   exit 1
-# fi
+if grep -qE "${CHANGELOG} \([0-9]{4}-[0-9]{1,2}-[0-9]{1,2}\)" CHANGELOG.md; then
+  :
+else
+  echo 'CHANGELOG.md: Missing or invalid date.'
+  exit 1
+fi
 
 ################################################################################
 # TO TEST THIS HOOK: uncomment statement below
